#include <iostream>
using namespace std;

class Car{
private:
    
public:

    string brand;
    string model;
    float rentalPrice;
    bool availability;
    float totalRevenue;
    string carID;

    Car(){
        brand = "unknown";
        model = "generic";
        rentalPrice = 0.0;
        availability = true;
    }

    Car(string brand, string model, float rentalPrice, bool availability){
        this->brand = brand;
        this->model = model;
        this->rentalPrice = rentalPrice;
        this->availability = availability;
    }

    Car(Car &obj){
        this->brand = obj.brand;
        this->model = obj.model;
        this->rentalPrice = obj.rentalPrice;
        this->availability = obj.availability;
    }

    Car(string id, string b, string m, float price, bool avail, float revenue = 0.0) 
    : carID(id), brand(b), model(m), rentalPrice(price), availability(avail), totalRevenue(revenue) {}

    ~Car() {
        cout << "Car object (" << brand << " " << model << ") removed from memory." << endl;
    }
    

    void setBrand(string brand){
        this->brand = brand;
    }

    void setModel(string model){
        this->model = model;
    }

    void setRentalPrice(float rentalPrice){
        this->rentalPrice = rentalPrice;
    }

    void setAvailability(bool availability){
        this->availability = availability;
    }

    bool checkAvailability(){
        return availability;
    }

    void processRequest(int days){
        if(availability==true){
            cout<<"you have succesfully rented the car"<<endl;
            totalRevenue += rentalPrice*days;
            availability = false;
        }else{
            cout<<"the car is already rented"<<endl;
        }
    }
 
    void applyDiscount(int days){
        if(availability) {
            if(days > 5 && days < 10) {
                rentalPrice *= 0.95; 
                cout << "5 percent discount applied. New rental price: " << rentalPrice << endl;
            } else if(days >= 10) {
                rentalPrice *= 0.90;
                cout << "10 percent discount applied. New rental price: " << rentalPrice << endl;
            }
        } else {
            cout << "Car is already rented" << endl;
        }
    }
    
    void trackRevenue(){
        cout<<"the total revenue generated by the car is: "<<totalRevenue<<endl;
    }

    void displayCarDetails() {
        cout << "Car ID: " << carID << endl;
        cout << "Brand: " << brand << endl;
        cout << "Model: " << model << endl;
        cout << "Rental Price: $" << rentalPrice << " per day" << endl;
        cout << "Availability: " << (availability ? "Available" : "Rented") << endl;
        cout << "Total Revenue Generated: $" << totalRevenue << endl;
    }

};

int main(){

    return 0;
}